### PR TITLE
Fix application of fix-its replacing parent instead of first child

### LINKED ISSUE #15: Fix-it targeting first child node instead replaces parent syntax collection
### Description

When `assertMacro` applies a fix-it intended to replace the first node within a collection syntax type, the collection node is replaced instead. This results in the loss of nodes that were not targeted by the fix-it.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-macro-testing/issues) or [discussion](https://github.com/pointfreeco/swift-macro-testing/discussions).

### Expected behavior

This original source:

```swift
@ReplaceFirstMember
struct FooBar {
  let foo: Foo
  let bar: Bar
  let baz: Baz
}
```

should have the following snapshotted `fixes` content:

```swift
@ReplaceFirstMember
struct FooBar {
  let oye: Oye
  let bar: Bar
  let baz: Baz
}
```

### Actual behavior

Incorrect snapshotted `fixes` content:

```swift
@ReplaceFirstMember
struct FooBar {
  let oye: Oye
}
```

### Steps to reproduce

1. Create a struct with multiple members.
2. Apply a fix-it to replace the first member of the struct.
3. Observe that all members are replaced, not just the targeted member.

Here's a test that reproduces the problem. Note the content of `fixes`:

```swift
import MacroTesting
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros
import XCTest

fileprivate enum ReplaceFirstMemberMacro: MemberMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingMembersOf declaration: some DeclGroupSyntax,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard
      let nodeToReplace = declaration.memberBlock.members.first,
      let newNode = try? MemberBlockItemSyntax(
        decl: VariableDeclSyntax(SyntaxNodeString(stringLiteral: "\n  let oye: Oye"))
      )
    else { return [] }

    context.diagnose(
      Diagnostic(
        node: node.attributeName,
        message: SimpleDiagnosticMessage(
          message: "First member needs to be replaced",
          diagnosticID: MessageID(domain: "domain", id: "diagnostic2"),
          severity: .warning
        ),
        fixIts: [
          FixIt(
            message: SimpleDiagnosticMessage(
              message: "Replace the first member",
              diagnosticID: MessageID(domain: "domain", id: "fixit1"),
              severity: .error
            ),
            changes: [
              .replace(oldNode: Syntax(nodeToReplace), newNode: Syntax(newNode))
            ]
          )
        ]
      )
    )

    return []
  }
}

final class ReplaceMemberMacroTests: BaseTestCase {
  override func invokeTest() {
    withMacroTesting(macros: [ReplaceFirstMemberMacro.self]) {
      super.invokeTest()
    }
  }

  func testReplaceFirstMember() {
    assertMacro {
      """
      @ReplaceFirstMember
      struct FooBar {
        let foo: Foo
        let bar: Bar
        let baz: Baz
      }
      """
    } diagnostics: {
      """
      @ReplaceFirstMember
       ┬─────────────────
       ╰─ ⚠️ First member needs to be replaced
          ✏️ Replace the first member
      struct FooBar {
        let foo: Foo
        let bar: Bar
        let baz: Baz
      }
      """
    } fixes: {
      """
      @ReplaceFirstMember
      struct FooBar {
        let oye: Oye
      }
      """
    } expansion: {
      """
      struct FooBar {
        let oye: Oye
      }
      """
    }
  }
}
```

### swift-macro-testing version information

0.2.0, main (6e93798)

### Destination operating system

macOS 14.2

### Xcode version information

Xcode Version 15.1 (15C65)

### Swift Compiler version information

```shell
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

### PR DESCRIPTION
**Pull request by gohanlon**
This fixes #15 by pulling in the latest `FixItApplier` from swift-syntax `main` (d647052), which is now String-based.

* For review, I left an intermediate commit showing how the new test fails before the fix. I’m happy to squash that commit into the fix before merging.
* I added “Bump deps” opportunistically, but this PR doesn’t depend on it. Let me know if you’d rather do that outside of this PR.

Note:
* The upstream [`FixItApplier`](https://github.com/apple/swift-syntax/blob/d647052/Sources/_SwiftSyntaxTestSupport/FixItApplier.swift) has undergone a complete rework in swift-syntax `main`. It’s now `String`-based rather than `SyntaxRewriter`-based. (It’s publicly accessible but not exposed as a product within the underscored `_SwiftSyntaxTestSupport` module, an “internal helper target”.)
* The upstream `FixItApplier.applyFixes` function isn’t needed by swift-macro-testing, and omitting it allows [these two extensions on `FixIt`](https://github.com/apple/swift-syntax/blob/d647052/Sources/SwiftDiagnostics/FixIt.swift#L50) to be omitted.
* `SwiftSyntax/SourceEdit` is public but hasn't been released, so eventually it can be removed from swift-macro-testing.

### CODE REVIEW

**Comment by gohanlon** [comment]
Also for consideration, see a disfavored alternative approach: [fix-it-applier-compare-kind](https://github.com/gohanlon/swift-macro-testing/tree/fix-it-applier-compare-kind). While interesting, I think it ultimately reinforces this PR's solution.

In this alternative, I'd independently arrived at the same simple solution that #12 initially had but [removed before merging](https://github.com/pointfreeco/swift-macro-testing/pull/12/files/a6658b12dc0fb713ca94cddf64aa079b9c771470#diff-0dc23da18126fa55ed5de9990ef69a33d2a11093a694d08139d23014c0ff4bff). However, because `oldNode.id == node.id` is never true (I think because the old and/or new nodes have been re-rooted), I suspect that `visit(_: TokenSyntax) -> TokenSyntax` needs to also be modified to also work on offsets and node kind. Further, neither swift-macro-testing nor my own projects use or have test coverage for `.replaceLeadingTrivia/.replaceTrailingTrivia`, so my inclination is to keep better alignment with the upstream. Plus, I expect/hope `FixItApplier` will eventually become publicly available.

File: Sources/MacroTesting/AssertMacro.swift [hunk 1]
```diff
@@ -343,6 +349,57 @@ public func assertMacro(
   }
 }
 
+// From: https://github.com/apple/swift-syntax/blob/d647052/Sources/SwiftSyntaxMacrosTestSupport/Assertions.swift
```
Comment (stephencelis) [inline Sources/MacroTesting/AssertMacro.swift:352]: Instead of inlining these in the library, what do you think of putting it in a file in the `SwiftSyntax` directory alongside `SourceEdit`, etc.?

**Review by stephencelis — APPROVED** [review]
Looks great! Just one small thing. Wanna tackle it before we merge?

File: Sources/MacroTesting/AssertMacro.swift (hunk 1 above)
Comment (gohanlon) [reply Sources/MacroTesting/AssertMacro.swift:352]: Sure, I'm happy to do that. I didn't do so initially because the upstream extensions are `fileprivate` and kept close to the asserts that use them. Plus, these two extensions are just a small parts of their larger upstream file, and I think files from upstream have so far been pulled in wholesale with minimal alterations.

Here are the upstream extensions' signatures from `SwiftSyntax`'s `SwiftSyntaxMacrosTestSupport/Assertions.swift`:

```swift
extension FixIt.Change {
  fileprivate func edit(
    in expansionContext: BasicMacroExpansionContext
  ) -> SourceEdit {
    …
  }
}
```

```swift
extension BasicMacroExpansionContext {
  fileprivate func position(
    of position: AbsolutePosition,
    anchoredAt node: some SyntaxProtocol
  ) -> AbsolutePosition {
    …
  }
}
```

I think it'd be okay to make the extensions `internal` instead of `fileprivate`. Here are some options:

1. Since `BasicMacroExpansionContext` is common between the two extensions, make the extensions `internal` and add them to a new file: `Sources/SwiftSyntax/SourceEditMacroExpansion.swift`.
2. Make the extensions `internal` and them directly to `Sources/SwiftSyntax/SourceEdit.swift`.
3. If you'd rather leave them in `AssertMacro.swift` as `fileprivate`, I can move them to the end of the file.

For me to move forward, feel free to pick one of these ideas or throw in another that you think might work better. Looking forward to your input!

**Review by stephencelis — APPROVED** [review]
I think you've convinced me that moving the methods is probably not worth it :smile:
